0.2.1
internet checks

diff --git a/geoloc b/geoloc
--- a/geoloc
+++ b/geoloc
@@ -1,7 +1,7 @@
 #!/bin/zsh
 # shellcheck shell=bash
 
-# geoloc v0.2
+# geoloc v0.2.1
 
 if [[ $(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I 2>/dev/null) == "AirPort: Off" ]] ; then
 	echo "Error: WiFi disabled" >&2
@@ -103,6 +103,10 @@ EOF
 )
 if ! [[ $geoloc_all ]] ; then
 	$debug && echo "Error: osascript"
+	if ! [[ $(route get 0.0.0.0 2>/dev/null) ]] ; then
+		echo "Error: no internet" >&2
+		exit 1
+	fi
 	queryurl="https://api.mylnikov.org/geolocation/wifi?v=1.1&data=open&search="
 	closestwifis=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s | grep ":" | head -13)
 	if ! [[ $closestwifis ]] ; then
@@ -188,6 +192,10 @@ fi
 echo "$latitude $longitude"
 if [[ $1 != "--solar" ]] ; then
 	exit 0
+fi
+if ! [[ $(route get 0.0.0.0 2>/dev/null) ]] ; then
+	echo "Error: no internet" >&2
+	exit 1
 fi
 solar_all=$(curl -s -m 60 "v2.wttr.in/$latitude,$longitude?format=%S;%s" 2>/dev/null)
 if ! [[ $solar_all ]] ; then
